== Con
:Author:    Andreas Krantz
:Email:     totonga@gmail.com

****
Con is hard to explain. It is a mixture of context, configuration, connection, factory and session.
I like configuration the best because it defines how the current user will access the server by mean
of what is configurable for this server.
****

=== Create new Con

----
POST /con/{conI}
----

.create new Con
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '[
    {
        "name": "$URL",
        "value": "corbaname::localhost:2809/NameService#AtfxTest.ASAM-ODS"
    },
    {
        "name": "USER",
        "value": "System"
    },
    {
        "name": "PASSWORD",
        "value": "puma"
    }
]' 'http://localhost:8081/con/myCon'
----
================================


=== Change/Update Con Parameters

----
PUT /con/{conI}
----

TIP: A PUT call to a Con with empty parameters will close an active session. Be aware that any open transaction will be aborted!
TIP: PUT will create the entry if it does not exist

.update Con parameters
================================
.request
[source,json]
----
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '[
    {
        "name": "$URL",
        "value": "corbaname::localhost:2809/NameService#AtfxTest.ASAM-ODS"
    },
    {
        "name": "USER",
        "value": "System"
    },
    {
        "name": "PASSWORD",
        "value": "puma"
    }
]' 'http://localhost:8081/con/c1'
----
================================

.close open AoSession on Con myCon without deleting myCon
================================
.request
[source,json]
----
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '[]' 'http://localhost:8081/con/myCon'
----
================================


=== Delete Con

----
DELETE /con/{conI}
----

.read all parameters
================================
.request
[source,json]
----
curl -X DELETE --header 'Content-Type: application/json' --header 'Accept: application/problem+json' 'http://localhost:8081/con/c1'
----

.result
[source,json]
----
----
================================


=== Read Con Parameters

----
GET /con/{conI}
----

.read all parameters
================================
.request
[source,json]
----
curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/problem+json' 'http://localhost:8081/con/c1'
----

.result
[source,json]
----
[
    {
        "name": "$URL",
        "value": "corbaname::localhost:2809/NameService#AtfxTest.ASAM-ODS"
    },
    {
        "name": "USER",
        "value": "System"
    }
]
----
================================

=== Get List of Con Entries

----
GET /con
----

.read all parameters
================================
.request
[source,json]
----
curl -X GET --header 'Accept: application/problem+json' 'http://localhost:8081/con'
----

.result
[source,json]
----
----
================================
