== Data
:Author:    Andreas Krantz
:Email:     totonga@gmail.com

****
ASAM ODS is about making measurement data persistent. So this is the most important chapter. Its is about writing and reading data (meta/bulk).
****

include::datamatrix.adoc[]


=== Read meta data

----
POST /con/{conI}/data/access
----

.get results from first entity derived from AoTest with all properties
================================
TIP: The server will have a default rowMaxCount setting.
     He will potentially not return all AoTest if there are more of them.
     
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "AoTest"
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get results from instances with objecttype 1 with all properties
================================
TIP: Using the objecttype will give no great speed improvement. It is not even readable.
     
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "1"
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get results of instances with objecttype MeaQuantity and define the maximal number of rows to return
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "rowMaxCount": 50
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get id and name attribute of the given entity
================================
TIP: if an instance should be shown in a tree it is sufficient to retrieve name and id

.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "name",
        "id"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get id and name attribute of the given entity and the name attribute of the related measurement
================================
TIP: if an instance should shown it might be usefult to retrieve some parent/related attributes

.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "name",
        "id",
        "measurement.name"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================


.get all attributes if for a given instance
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "conditions": [
        "id=4"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get children MeasurementQuantities of the Measurement with id=2
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "name",
        "id"
    ],
    "conditions": [
        "measurement=2"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.Get information about all MeasurementQuantities of a the SubTest with id=2
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "name",
        "id",
        "measurement.name",
        "measurement.id"
    ],
    "conditions": [
        "measurement.test=2"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get some measurementquantities and related info using a query
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
    "entity": "AoMeasurementQuantity",
    "conditions": [
        "measurement.measurement_begin > 20090101000000",
        "$and",
        "$open",
        "name=Uctf_String",
        "$or",
        "name=Uctf_Time",
        "$close"
    ],
    "attributes": [
        "name",
        "id",
        "unit",
        "measurement.name",
        "measurement.id",
        "measurement.test.name",
        "measurement.test.id"
    ]
}' 'http://localhost:8081/con/c2/data/access'
----
.result
[source,json]
----
----
================================

.get DISTINCT of all MeasurementQuantity names
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "DISTINCT(name)"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get names of given entity in descending order
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "MeaQuantity",
    "attributes": [
        "name"
    ],
    "orderBy": [
        "DESCENDING(name)"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.get names of measurementquantities grouped and ordered by name
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{
    "entity": "AoMeasurementQuantity",
    "attributes": [
        "name"
    ],
    "orderBy": [
        "name"
    ],
    "groupBy": [
        "name"
    ]
}' 'http://localhost:8081/con/c2/data/access'
----
.result
[source,json]
----
----
================================

=== Read bulk data

----
POST /con/{conI}/data/access
----

****
When bulk data is returned the AoLocalColumn::values attribute is used. It has type DT_UNKNOWN. So the values
will be returned in unkownSeq which allows different types for each result row.
****

.Get values, flags and generation_parameters of the given localcolumn
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "AoLocalColumn",
    "conditions": [
        "id=12"
    ],
    "attributes": [
        "id",
        "values",
        "flags",
        "generation_parameters"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.Get id, values, flags and generation_parameters of all local columns of the Submatrix with id=8, but return maximal 1000 sequence rows
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "LocalColumn",
    "conditions": [
        "submatrix=8"
    ],
    "attributes": [
        "id",
        "values",
        "flags",
        "generation_parameters"
    ],
    "seqMaxCount": 1000
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.Get next chunk id, values and flags of all local columns of the Submatrix with id=8
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "LocalColumn",
    "conditions": [
        "submatrix=8"
    ],
    "attributes": [
        "id",
        "values",
        "flags",
        "generation_parameters"
    ],
    "seqSkipCount": 1000,
    "seqMaxCount": 1500
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================

.Get id, values, flags and generation_parameters of all local column Time and Revs of the Submatrix with id=8
================================
.request
[source,json]
----
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '
{
    "entity": "LocalColumn",
    "conditions": [
        "submatrix=8",
        "$and",
        "$open",
        "name=Time",
        "$or",
        "name=Revs",
        "$close"
    ],
    "attributes": [
        "id",
        "values",
        "flags",
        "generation_parameters"
    ]
}' 
'http://localhost:8081/con/c1/data/access'
----
.result
[source,json]
----
----
================================


=== Write meta data

----
POST /con/{conI}/data/modify
PUT /con/{conI}/data/modify
DELETE /con/{conI}/data/modify
----

==== Create new instances

----
POST /con/{conI}/data/modify
----

==== Update instances

----
PUT /con/{conI}/data/modify
----

==== Delete Instances

----
DELETE /con/{conI}/data/modify
----


=== Write bulk data

----
PUT /con/{conI}/data/modify
----
