=== Jaquel
:Author:    Andreas Krantz
:Email:     totonga@gmail.com

****
MongoDb uses a json based flexible query structure that allows a good learning 
curve because of a simple form for every day jobs. Inspired by this, the idea for this
approach came up.
****

IMPORTANT: It is always possible to use application or base names for entity, relations, attributes. 
           Order is 1.) application 2.) base. If base name is not uniquely assigned in the model one of the vector is picked. 
           This is important for writing generic code even without having to analyze the complete model.
           Be aware that application name can always be used to access any element or attribute.

==== Json Query Language

.get all Aotests
[source,json]
-----------
{
    "AoTest": {}
}
-----------

.access instances using id only
=============================

.get measurement with id 4711
[source,json]
-----------
{
    "AoMeasurement": 4711
}
-----------

[source,json]
-----------
{
    "AoMeasurement": "4711"
}
-----------

[source,json]
-----------
{
    "AoMeasurement": {
        "id": "4711"
    }
}
-----------

[source,json]
-----------
{
    "AoMeasurement": {
        "id": 4711
    }
}
-----------

.get children of a given subtest
==============================

[source,json]
-----------
{
    "AoMeasurement": {
        "test": 4611
    }
}
-----------

[source,json]
-----------
{
    "AoMeasurement": {
        "test.id": 4611
    }
}
-----------

TIP: `test.id` is a duplicate because the id is also stored in test column

.use inverse to do the same job
===============================

[source,json]
-----------
{
    "AoSubTest": "4611",
    "$attributes": {
        "children.name": 1,
        "children.id": 1
    }
}
-----------

[source,json]
-----------
{
    "AoSubTest": "4611",
    "$attributes": {
        "children": {
            "name": 1,
            "id": 1
        }
    }
}
-----------

===============================
==============================
=============================

.search for a AoTest by name and version
[source,json]
-----------
{
    "AoTest": {
        "name": "MyTest",
        "version": "V1"
    }
}
-----------

.case insensitive match 
[source,json]
-----------
{
    "AoTest": {
        "name": {
            "$eq": "MyTest",
            "$options": "i"
        }
    }
}
-----------

.case insensitive match 
[source,json]
-----------
{
    "AoTest": {
        "name": {
            "$like": "My*",
            "$options": "i"
        }
    }
}
-----------

.resolve asam path
[source,json]
-----------
{
    "AoMeasurement": {
        "name": "MyMea",
        "version": "V1",
        "test.name": "MySubTest2",
        "test.version": "V1",
        "test.parent_test.name": "MySubTest1",
        "test.parent_test.version": "V1",
        "test.parent_test.parent_test.name": "MyTest",
        "test.parent_test.parent_test.version": "V1"
    }
}
-----------

.resolve asam path
[source,json]
-----------
{
    "AoMeasurement": {
        "name": "MyMea",
        "version": "V1",
        "test": {
            "name": "MySubTest2",
            "version": "V1",
            "parent_test": {
                "name": "MySubTest1",
                "version": "V1",
                "parent_test": {
                    "name": "MyTest",
                    "version": "V1"
                }
            }
        }
    }
}
-----------

.use $in operator
[source,json]
-----------
{
    "AoMeasurement": {
        "id": {
            "$in": [
                4711,
                4712,
                4713
            ]
        }
    }
}
-----------

.search for a time span
[source,json]
-----------
{
    "AoMeasurement": {
        "measurement_begin": {
            "$gte": "2012-04-23T00:00:00.000Z",
            "$lt": "2012-04-24T00:00:00.000Z"
        }
    }
}
-----------

.use between operator
[source,json]
-----------
{
    "AoMeasurement": {
        "measurement_begin": {
            "$between": [
                "2012-04-23T00:00:00.000Z",
                "2012-04-24T00:00:00.000Z"
            ]
        }
    }
}
-----------

.simple $and example
[source,json]
-----------
{
    "AoMeasurement": {
        "$and": [
            {
                "measurement_begin": {
                    "$gte": "2012-04-23T00:00:00.000Z",
                    "$lt": "2012-04-24T00:00:00.000Z"
                }
            },
            {
                "measurement_end": {
                    "$gte": "2012-04-23T00:00:00.000Z",
                    "$lt": "2012-04-24T00:00:00.000Z"
                }
            }
        ]
    }
}
-----------

.simple or example
[source,json]
-----------
{
    "AoMeasurement": {
        "$or": [
            {
                "measurement_begin": {
                    "$gte": "2012-04-23T00:00:00.000Z",
                    "$lt": "2012-04-24T00:00:00.000Z"
                }
            },
            {
                "measurement_begin": {
                    "$gte": "2012-05-23T00:00:00.000Z",
                    "$lt": "2012-05-24T00:00:00.000Z"
                }
            },
            {
                "measurement_begin": {
                    "$gte": "2012-06-23T00:00:00.000Z",
                    "$lt": "2012-06-24T00:00:00.000Z"
                }
            }
        ]
    }
}
-----------

.simple $not example
[source,json]
-----------
{
    "AoMeasurement": {
        "$not": {
            "$and": [
                {
                    "name": "MyMea"
                },
                {
                    "version": "V1"
                }
            ]
        }
    }
}
-----------


.mixed case sensitive/insensitive  
[source,json]
-----------
{
    "AoTest": {
        "$and": [
            {
                "name": {
                    "$like": "My*",
                    "$options": "i"
                }
            },
            {
                "name": {
                    "$like": "??Test"
                }
            }
        ]
    }
}
-----------

.define unit for attribute to be retrieved
[source,json]
-----------
{
    "AoMeasurement": 4711,
    "$attributes": {
        "name": 1,
        "id": 1,
        "scale": {
            "$unit": 123
        }
    }
}
-----------

.access $min and $max from minimum and maximum
[source,json]
-----------
{
    "AoMeasurementQuantity": {
        "name": "Revs"
    },
    "$attributes": {
        "minimum": {
            "$min": 1,
            "$max": 1
        },
        "maximum": {
            "$min": 1,
            "$max": 1
        }
    }
}
-----------

.do a full query filling some query elements
[source,json]
-----------
{
    "AoMeasurement": {
        "$or": [
            {
                "measurement_begin": {
                    "$gte": "2012-04-23T00:00:00.000Z",
                    "$lt": "2012-04-24T00:00:00.000Z"
                }
            },
            {
                "measurement_begin": {
                    "$gte": "2012-05-23T00:00:00.000Z",
                    "$lt": "2012-05-24T00:00:00.000Z"
                }
            },
            {
                "measurement_begin": {
                    "$gte": "2012-06-23T00:00:00.000Z",
                    "$lt": "2012-06-24T00:00:00.000Z"
                }
            }
        ]
    },
    "$options": {
        "$rowlimit": 1000,
        "$rowskip": 500
    },
    "$attributes": {
        "name": 1,
        "id": 1,
        "test": {
            "name": 1,
            "id": 1
        }
    },
    "$orderby": {
        "test.name": 0,
        "name": 1
    },
    "$groupby": {
        "id": 1
    }
}
-----------

[source,json]
-----------
{
    "AoMeasurement": {},
    "$attributes": {
        "name": {
            "$distinct": 1
        }
    }
}
-----------

.retrieve enumerations as strings instead of int
[source,json]
-----------
{
  "AoMeasurementQuantity": {},
  "$attributes": {
    "datatype": {
      "$options": "e"
    }
  }
}
-----------

.retrieve AoParameters and fill results in unknownSeq instead of stringVal
[source,json]
-----------
{
    "AoParameter": {},
    "$attributes": {
        "name": 1,
        "parameter_datatype": 1,
        "pvalue": {
            "$options": "u"
        }
    },
    "$options": {
        "$rowlimit": 100
    }
}
-----------


==== Special key values

.top level
|===========================================
| $attributes | list of attributes to retrieve
| $orderby    | order the results by this 1 ascending 0 decending
| $groupby    | group the results by this
| $options    | global options
|===========================================

.conjuctions
|===========================================
| $and | connect array elements with logical AND. Contains Array of expressions.
| $or  | connect array elements with logical OR. Contains Array of expressions.
| $not | invert result of object. Contains single expression
|===========================================

.operators
|===========================================
| $eq          | equal
| $neq         | not equal
| $lt          | lesser than
| $gt          | greater than
| $lte         | lesser than equal
| $gte         | greater than equal
| $in          | contained in array
| $notin       | not contained in array
| $like        | equal using wildcards *?
| $notlike     | not equal using wildcards *?
| $null        | is null value ("$null":1)
| $notnull     | not is null value ("$notnull":1)
| $between     | two values in an array. Equal to a $gte $lt pair
| $options     | string containing letters: `i` for case insensitive
|===========================================

.aggregates
|===========================================
| $count     | return int containing the number of rows
| $dcount    | return int containing the number of distincted rows
| $min       | returns minimal value of the attribute
| $max       | returns maximal value of the attribute
| $avg       | returns average value of the attribute
| $stddev    | returns standard derivation value of the attribute
| $sum       | returns sum of all attribute values
| $distinct  | distinct attribute values
| $point     | used for query on bulk data. returning indices of local column values
| $options   | string containing letters: `e` enum values as string (json only), `u` fill pValue into unkownSeq instead of strVal, `n` return int64 as number instead of string (json only)
| $calculated| can only be used for AoLocalColumn.values to expand implicit and raw scaled channels
| $unit      | define the unit by its id that should be used for the return values
|===========================================

.global options
|===========================================
| $rowlimit    | maximal number of rows to return
| $rowskip     | number of rows to be skipped
| $seqlimit    | maximal number of entries in a single sequence
| $seqskip     | number of entries to be skipped in a single sequence
|===========================================

