== Model
:Author:    Andreas Krantz
:Email:     totonga@gmail.com

****
The physical storage of an ASAM ODS server is a relational database.
The model contains the entity relationship definitions (ERM) needed to retrieve the stored data sensful.
****

TIP: The model is the schema of the ASAM ODS Server

=== Get model

----
GET /con/{conI}/model
----

****
If a client is not hard coded against a model, it should retrieve the model in 
one piece and use local source code to extract information from the model.
****

IMPORTANT: The model should be cached and not retrieved every time.

.retrieve the model
================================
.request
[source,json]
----
curl -X GET --header 'Content-Type: application/json' --header 'Accept: application/problem+json' 'http://localhost:8081/con/c1/model'
----

.result
[source,json]
----
----
================================

TIP: The content of the model needs to be known to fill later request to *data* resource.


=== Modify model

----
PUT /con/{conI}/model
DELETE /con/{conI}/model
----

==== Add components

----
PUT /con/{conI}/model
----

.create entity *MyAny*
================================
.request
[source,json]
----
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '{
    "entities": [
        {
            "name": "MyAny",
            "baseName": "AoAny",
            "relations": [
                {
                    "name": "myMeasurment",
                    "inverseName": "myInfoElement",
                    "obligatory": false,
                    "type": "n-1",
                    "relEntityName": "Measurement"
                }
            ],
            "attributes": [
                {
                    "name": "Id",
                    "baseName": "id"
                },
                {
                    "name": "Name",
                    "baseName": "name"
                },
                {
                    "name": "my_classification",
                    "dataType": "DT_DOUBLE",
                    "obligatory": true
                }
            ]
        }
    ]
}' 'http://localhost:8081/con/c1/model'
----
================================

.add attribute *my_value* to *MyAny*
================================
.request
[source,json]
----
curl -X PUT --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '{
    "entities": [
        {
            "name": "MyAny",
            "attributes": [
                {
                    "name": "my_value",
                    "dataType": "DT_DOUBLE",
                    "obligatory": true
                }
            ]
        }
    ]
}' 'http://localhost:8081/con/c1/model'
----
================================


==== Remove components

----
DELETE /con/{conI}/model
----

.delete attribute *my_value* at *MyAny*
================================
.request
[source,json]
----
curl -X DELETE --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '{
    "entities": [
        {
            "name": "MyAny",
            "attributes": [
                {
                    "name": "my_value"
                }
            ]
        }
    ]
}' 'http://localhost:8081/con/c1/model'
----
================================


.delete entity *MyAny*
================================
.request
[source,json]
----
curl -X DELETE --header 'Content-Type: application/json' --header 'Accept: application/problem+json' -d '{
    "entities": [
        {
            "name": "MyAny"
        }
    ]
}' 'http://localhost:8081/con/c1/model'
----
================================
