"""Load the ASAM ODS base model from the shipped JSON file."""

from __future__ import annotations

import json
import logging
from pathlib import Path

import odsbox.proto.ods_pb2 as ods

_log = logging.getLogger(__name__)

_BASE_MODEL_PATH = Path(__file__).resolve().parent / "base_model" / "ODSBaseModel_asam37.protobuf.json"


def load_base_model(path: Path | None = None) -> ods.BaseModel:
    """Load the ODS base model from a JSON file.

    The JSON structure mirrors the protobuf BaseModel message layout
    but uses a slightly different naming convention, so we manually
    parse rather than using ParseDict.
    """
    json_path = path if path is not None else _BASE_MODEL_PATH
    _log.debug("Loading base model from %s", json_path)
    with open(json_path, encoding="utf-8") as f:
        data: dict[str, object] = json.load(f)

    base_model = ods.BaseModel()
    base_model.version = str(data.get("version", ""))

    # Enumerations
    enums_data = data.get("enumerations")
    if isinstance(enums_data, dict):
        for enum_name, enum_obj in enums_data.items():
            if not isinstance(enum_obj, dict):
                continue
            enum_entry = base_model.enumerations[enum_name]
            enum_entry.name = str(enum_obj.get("name", enum_name))
            items = enum_obj.get("items")
            if isinstance(items, dict):
                for item_name, item_value in items.items():
                    enum_entry.items[item_name] = int(item_value)

    # Entities
    entities_data = data.get("entities")
    if isinstance(entities_data, dict):
        for entity_name, entity_obj in entities_data.items():
            if not isinstance(entity_obj, dict):
                continue
            entity = base_model.entities[entity_name]
            entity.name = str(entity_obj.get("name", entity_name))
            entity.bid = int(entity_obj.get("bid", 0))

            derivation_str = str(entity_obj.get("derivation", "DV_UNRESTRICTED"))
            derivation_map: dict[str, int] = {
                "DV_UNRESTRICTED": 0,
                "DV_SINGLE": 1,
                "DV_TREE_AT_INSTANCE": 2,
                "DV_TREE_AT_MODEL": 3,
            }
            entity.derivation = derivation_map.get(derivation_str, 0)  # type: ignore[assignment]

            # Attributes
            attrs_data = entity_obj.get("attributes")
            if isinstance(attrs_data, dict):
                for attr_name, attr_obj in attrs_data.items():
                    if not isinstance(attr_obj, dict):
                        continue
                    attr = entity.attributes[attr_name]
                    attr.name = str(attr_obj.get("name", attr_name))
                    attr.data_type = _parse_datatype(  # type: ignore[assignment]
                        str(attr_obj.get("dataType", "DT_UNKNOWN"))
                    )
                    attr.mandatory = bool(attr_obj.get("mandatory", False))
                    attr.obligatory = bool(attr_obj.get("obligatory", False))
                    attr.autogenerated = bool(attr_obj.get("autogenerated", False))
                    attr.enumeration = str(attr_obj.get("enumeration", ""))

            # Relations
            rels_data = entity_obj.get("relations")
            if isinstance(rels_data, dict):
                for rel_name, rel_obj in rels_data.items():
                    if not isinstance(rel_obj, dict):
                        continue
                    rel = entity.relations[rel_name]
                    rel.name = str(rel_obj.get("name", rel_name))
                    rel.inverse_name = str(rel_obj.get("inverseName", ""))
                    entity_names = rel_obj.get("entityNames")
                    if isinstance(entity_names, list) and len(entity_names) > 0:
                        rel.entity_names.extend([str(n) for n in entity_names])
                    rel.range_min = int(rel_obj.get("rangeMin", 0))
                    rel.range_max = int(rel_obj.get("rangeMax", -1))
                    rel.mandatory = bool(rel_obj.get("mandatory", False))
                    rel.inverse_range_min = int(rel_obj.get("inverseRangeMin", 0))
                    rel.inverse_range_max = int(rel_obj.get("inverseRangeMax", -1))

                    relationship_str = str(rel_obj.get("relationship", "RS_INFO_TO"))
                    relationship_map: dict[str, int] = {
                        "RS_FATHER": 0,
                        "RS_CHILD": 1,
                        "RS_INFO_TO": 2,
                        "RS_INFO_FROM": 3,
                        "RS_INFO_REL": 4,
                        "RS_SUPERTYPE": 5,
                        "RS_SUBTYPE": 6,
                        "RS_ALL_REL": 7,
                    }
                    rel.relationship = relationship_map.get(relationship_str, 2)  # type: ignore[assignment]

                    relation_type_str = str(rel_obj.get("relationType", "RT_INFO"))
                    relation_type_map: dict[str, int] = {
                        "RT_FATHER_CHILD": 0,
                        "RT_INFO": 1,
                        "RT_INHERITANCE": 2,
                    }
                    rel.relation_type = relation_type_map.get(relation_type_str, 1)  # type: ignore[assignment]

    return base_model


def _parse_datatype(dt_str: str) -> int:
    """Map datatype string to ods.DataTypeEnum int value."""
    mapping: dict[str, int] = {
        "DT_UNKNOWN": 0,
        "DT_STRING": 1,
        "DT_SHORT": 2,
        "DT_FLOAT": 3,
        "DT_BOOLEAN": 4,
        "DT_BYTE": 5,
        "DT_LONG": 6,
        "DT_DOUBLE": 7,
        "DT_LONGLONG": 8,
        "DT_DATE": 10,
        "DT_BYTESTR": 11,
        "DT_BLOB": 12,
        "DT_COMPLEX": 13,
        "DT_DCOMPLEX": 14,
        "DS_STRING": 15,
        "DS_SHORT": 16,
        "DS_FLOAT": 17,
        "DS_BOOLEAN": 18,
        "DS_BYTE": 19,
        "DS_LONG": 20,
        "DS_DOUBLE": 21,
        "DS_LONGLONG": 22,
        "DS_COMPLEX": 23,
        "DS_DCOMPLEX": 24,
        "DS_DATE": 26,
        "DS_BYTESTR": 27,
        "DT_EXTERNALREFERENCE": 28,
        "DS_EXTERNALREFERENCE": 29,
        "DT_ENUM": 30,
        "DS_ENUM": 31,
    }
    return mapping.get(dt_str, 0)
