"""Build an ods.Model from ATFX application_model XML, supplemented by the BaseModel."""

from __future__ import annotations

import logging
import xml.etree.ElementTree as ET

import odsbox.proto.ods_pb2 as ods

from ._base_model import _parse_datatype
from ._xml_utils import _extract_ns, _find, _findall, _text

_log = logging.getLogger(__name__)

_ODS_NS_PREFIX = "http://www.asam.net/ODS/"
_ODS_NS_SUFFIX = "/Schema"


def detect_ods_version(root: ET.Element) -> str:
    """Extract the ODS schema version from the root element namespace.

    For example, ``http://www.asam.net/ODS/6.1.0/Schema`` yields ``"6.1.0"``.
    Returns an empty string if the namespace does not match the expected pattern.
    """
    ns = _extract_ns(root.tag)
    if ns and ns.startswith(_ODS_NS_PREFIX) and ns.endswith(_ODS_NS_SUFFIX):
        return ns[len(_ODS_NS_PREFIX) : -len(_ODS_NS_SUFFIX)]
    return ""


def build_model(root: ET.Element, base_model: ods.BaseModel) -> ods.Model:
    """Build an ods.Model protobuf from the ATFX XML root and the ODS base model."""
    model = ods.Model()
    _log.debug("Building application model")

    # Copy base model enumerations into application model
    for enum_name in base_model.enumerations:
        bm_enum = base_model.enumerations[enum_name]
        app_enum = model.enumerations[enum_name]
        app_enum.name = bm_enum.name
        for item_name in bm_enum.items:
            app_enum.items[item_name] = bm_enum.items[item_name]

    app_model_el = _find(root, "application_model")
    if app_model_el is None:
        return model

    # Parse application enumerations
    for enum_el in _findall(app_model_el, "application_enumeration"):
        enum_name = _text(enum_el, "name")
        if not enum_name:
            continue
        app_enum = model.enumerations[enum_name]
        app_enum.name = enum_name
        for item_el in _findall(enum_el, "item"):
            item_name = _text(item_el, "name")
            item_value = _text(item_el, "value")
            if item_name and item_value:
                app_enum.items[item_name] = int(item_value)

    # First pass: collect entity names and assign AIDs
    app_elements = _findall(app_model_el, "application_element")
    name_to_aid: dict[str, int] = {}
    aid_counter = 0
    element_data: list[tuple[str, str, ET.Element]] = []  # (name, basetype, element)

    for ae_el in app_elements:
        ae_name = _text(ae_el, "name")
        ae_basetype = _text(ae_el, "basetype")
        if not ae_name:
            continue
        aid_counter += 1
        name_to_aid[ae_name] = aid_counter
        element_data.append((ae_name, ae_basetype, ae_el))

    _log.info(
        "Model: %d entities, %d enumerations",
        len(element_data),
        len(model.enumerations),
    )

    # Second pass: build entities with attributes and relations
    for ae_name, ae_basetype, ae_el in element_data:
        aid = name_to_aid[ae_name]
        entity = model.entities[ae_name]
        entity.name = ae_name
        entity.base_name = ae_basetype
        entity.aid = aid

        # Look up base model entity for supplemental info
        bm_entity: ods.BaseModel.Entity | None = None
        if ae_basetype in base_model.entities:
            bm_entity = base_model.entities[ae_basetype]

        # Parse application attributes
        attr_id = 0
        for attr_el in _findall(ae_el, "application_attribute"):
            attr_name = _text(attr_el, "name")
            if not attr_name:
                continue
            attr_id += 1

            attr = entity.attributes[attr_name]
            attr.name = attr_name
            attr.id = attr_id

            base_attr_name = _text(attr_el, "base_attribute")
            attr.base_name = base_attr_name

            # Determine data type: from XML <datatype> or from base model
            dt_str = _text(attr_el, "datatype")
            if dt_str:
                attr.data_type = _parse_datatype(dt_str)  # type: ignore[assignment]
            elif base_attr_name and bm_entity and base_attr_name in bm_entity.attributes:
                attr.data_type = bm_entity.attributes[base_attr_name].data_type
            else:
                attr.data_type = ods.DataTypeEnum.DT_UNKNOWN

            # Obligatory
            oblig_str = _text(attr_el, "obligatory")
            if oblig_str:
                attr.obligatory = oblig_str.lower() == "true"
            elif base_attr_name and bm_entity and base_attr_name in bm_entity.attributes:
                attr.obligatory = bm_entity.attributes[base_attr_name].obligatory

            # Unique
            unique_str = _text(attr_el, "unique")
            if unique_str:
                attr.unique = unique_str.lower() == "true"

            # Autogenerated (from base model)
            if base_attr_name and bm_entity and base_attr_name in bm_entity.attributes:
                attr.autogenerated = bm_entity.attributes[base_attr_name].autogenerated

            # Length
            length_str = _text(attr_el, "length")
            if length_str:
                attr.length = int(length_str)

            # Enumeration
            enum_type_str = _text(attr_el, "enumeration_type")
            if enum_type_str:
                attr.enumeration = enum_type_str
            elif base_attr_name and bm_entity and base_attr_name in bm_entity.attributes:
                attr.enumeration = bm_entity.attributes[base_attr_name].enumeration

        # Parse relation attributes
        for rel_el in _findall(ae_el, "relation_attribute"):
            rel_name = _text(rel_el, "name")
            if not rel_name:
                continue

            rel = entity.relations[rel_name]
            rel.name = rel_name

            base_rel_name = _text(rel_el, "base_relation")
            rel.base_name = base_rel_name

            inverse_name = _text(rel_el, "inverse_name")
            rel.inverse_name = inverse_name

            # Target entity
            ref_to = _text(rel_el, "ref_to")
            if ref_to:
                rel.entity_name = ref_to
                if ref_to in name_to_aid:
                    rel.entity_aid = name_to_aid[ref_to]
                # Get target base name
                for other_name, other_base, _ in element_data:
                    if other_name == ref_to:
                        rel.entity_base_name = other_base
                        break

            # Range
            min_occurs_str = _text(rel_el, "min_occurs")
            max_occurs_str = _text(rel_el, "max_occurs")
            if min_occurs_str:
                rel.range_min = int(min_occurs_str)
            if max_occurs_str:
                rel.range_max = -1 if max_occurs_str.lower() == "many" else int(max_occurs_str)

            # Supplement from base model
            bm_rel: ods.BaseModel.Relation | None = None
            if base_rel_name and bm_entity and base_rel_name in bm_entity.relations:
                bm_rel = bm_entity.relations[base_rel_name]

            if bm_rel is not None:
                if not inverse_name:
                    rel.inverse_name = bm_rel.inverse_name
                # inverse base name
                rel.inverse_base_name = bm_rel.inverse_name

                # inverse range
                rel.inverse_range_min = bm_rel.inverse_range_min
                rel.inverse_range_max = bm_rel.inverse_range_max

                # relation type and relationship
                rel.relation_type = bm_rel.relation_type
                rel.relationship = bm_rel.relationship
            else:
                # Guess from min/max: if max==1 and min>=1, likely FATHER
                if rel.range_max == 1 and rel.range_min >= 1:
                    rel.relation_type = ods.Model.RelationTypeEnum.RT_FATHER_CHILD
                    rel.relationship = ods.Model.RelationshipEnum.RS_FATHER
                elif rel.range_max == -1:
                    rel.relation_type = ods.Model.RelationTypeEnum.RT_INFO
                    rel.relationship = ods.Model.RelationshipEnum.RS_INFO_FROM
                else:
                    rel.relation_type = ods.Model.RelationTypeEnum.RT_INFO
                    rel.relationship = ods.Model.RelationshipEnum.RS_INFO_TO

    return model
